github.com:
    users:
        dxomg:
            oauth_token: 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
    git_protocol: https
    oauth_token: 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
    user: dxomg
